# ==============================
#     REST API Configuration
# ==============================
server:
  servlet:
   context-path: /rest/api/v1

# ==============================
#     Spring Configurations
# ==============================
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: validate
    open-in-view: true

  # ==============================
  #     Database Configuration
  # ==============================
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # ==============================
  #     Flyway Configuration
  # ==============================
  flyway:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: postgres
    baseline-on-migrate: true
    enabled: true

# ==============================
#     Logging Configuration
# ==============================
logging:
  level:
    com.ditsov.basicschoolgradingsystem: DEBUG
    org:
      springframework:
        test: INFO
        web: INFO
        boot:
          autoconfigure:
            logging: OFF

# ==================================
#     Application Configurations
# ==================================
school-grading-system:
  token:
    header-name: Authorization # sets the token header name
    prefix: Bearer # sets the token prefix
    expiration: PT5M # sets the duration of the token
    secret-key: ADQq27g7B8HmKtaGyYoU # sets the token's default secret key
